; The Umbral Threshold
[meta]
name = The Umbral Threshold
next = configs/floor2.ini
enemy_scale = 1.0

[map]
width = 31
height = 21
row0 = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
row1 = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
row2 = XX......X.....X.....XXXXXXXXXXX
row3 = XX......X.....X.....XXXXXXXXXXX
row4 = XX......X...........XXXXXXXXXXX
row5 = XX............X.....XXXXXXXXXXX
row6 = XX......X.....X.....XXXXXXXXXXX
row7 = XX......X.....X.....XXXXXXXXXXX
row8 = XX......X.....X.....XXX......XX
row9 = XXXXX.XXXXX.XXXXX.XXXXX......XX
row10 = XX......X.................E..XX
row11 = XX............X.....XXX......XX
row12 = XX......X.....X.....XXX......XX
row13 = XX......X.....X.....XXX......XX
row14 = XX......X.....X.....XXXXXXXXXXX
row15 = XX......X...........XXXXXXXXXXX
row16 = XX............X.....XXXXXXXXXXX
row17 = XX......X.....X.....XXXXXXXXXXX
row18 = XX......X.....X.....XXXXXXXXXXX
row19 = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
row20 = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

[player]
x = 3
y = 3
hp = 20
attack = 5
defense = 0
gold = 20

[start_equipped]
e0 = weapon Shadow_Shard 1 0 0
e1 = shield Cracked_Aegis 0 1 0

[enemies]
e0 = goblin 11 3
e1 = goblin 17 3
e2 = goblin 5 13
e3 = goblin 11 16
e4 = hobgoblin 17 13

[boss]
b0 = golem 24 10

[boss_chests]
bc0 = 24 12 golem
bc1 = 27 12 treasure

[doors]
d0 = 22 10 boss

[items]
i0 = 5 5 potion Shadowmend 10
i1 = 11 5 weapon Umbral_Blade 3 0 0
i2 = 17 5 helmet Shadowhelm 0 2 5
i3 = 11 11 ring Ring_of_Umbra 1 0 0

[chests]
c0 = 5 17 keyvault
c1 = 17 17 wooden

[shopkeeper]
x = 17
y = 6

[shop]
s0 = 15 weapon Nightsteel_Sword 5 0 0
s1 = 20 armor Shadowplate 0 6 10
s2 = 8 potion Shadowmend 10
s3 = 18 shield Gloomwood_Shield 0 3 0
s4 = 30 doorkey Umbral_Key

[loot_goblin]
d0 = weapon Gloom_Dagger 2 0 0 0.5
d1 = chestkey Gloom_Key 0.5
d2 = gold 8 0.8

[loot_hobgoblin]
d0 = weapon Umbral_Blade 3 0 0 0.7
d1 = chestkey Gloom_Key 0.6
d2 = gold 25 1.0

[loot_golem]
d0 = weapon Duskhammer 8 0 0 1.0
d1 = armor Shadowplate 0 6 10 1.0
d2 = gold 100 1.0

[loot_treasure]
d0 = weapon Nightsteel_Sword 5 0 0 0.8
d1 = armor Shadowplate 0 6 10 0.6
d2 = potion Greater_Shadowmend 20 1.0
d3 = gold 50 1.0

[loot_wooden]
d0 = potion Shadowmend 10 0.8
d1 = gloves Shade_Gloves 0 1 0 0.5
d2 = gold 13 1.0

[loot_keyvault]
d0 = doorkey Umbral_Key 1.0
d1 = potion Shadowmend 10 0.7
d2 = gold 18 1.0