; The Shrouded Depths
[meta]
name = The Shrouded Depths
next = configs/floor3.ini
enemy_scale = 1.4

[map]
width = 31
height = 21
row0 = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
row1 = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
row2 = XX......X....X.....XXXXXXXXXXXX
row3 = XX......X....X.....XXXX......XX
row4 = XX......X..........XXXX......XX
row5 = XX......X....X...............XX
row6 = XX...........X.....XXXX......XX
row7 = XX......X....X.....XXXX......XX
row8 = XX......X....X.....XXXXXXXXXXXX
row9 = XXXXX.XXXXX.XXXX.XXXXXXXXXXXXXX
row10 = XX......X..........XXXXXXXXXXXX
row11 = XX......X....X.....XXXXXXXXXXXX
row12 = XX...........X.....XXXXXXXXXXXX
row13 = XX......X....X.....XXXX......XX
row14 = XX......X....X.....XXXX......XX
row15 = XX......X....X............E..XX
row16 = XX......X..........XXXX......XX
row17 = XX...........X.....XXXX......XX
row18 = XX......X....X.....XXXX......XX
row19 = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
row20 = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

[player]
x = 3
y = 3
hp = 20
attack = 5
defense = 0
gold = 20

[start_equipped]
e0 = weapon Shadow_Shard 1 0 0
e1 = shield Cracked_Aegis 0 1 0

[enemies]
e0 = knight 11 3
e1 = knight 17 3
e2 = archer 5 12
e3 = knight 17 12
e4 = archer 11 16
e5 = knight 5 17

[boss]
b0 = wyvern 27 15

[boss_chests]
bc0 = 24 17 wyvern
bc1 = 27 17 treasure

[doors]
d0 = 22 5 vault
d1 = 22 15 boss

[items]
i0 = 5 4 potion Shadowmend 10
i1 = 11 5 potion Greater_Shadowmend 20
i2 = 5 6 armor Shadowplate 0 6 10
i3 = 11 11 amulet Amulet_of_Dusk 2 1 5
i4 = 5 11 boots Gloomstep_Boots 0 1 0

[chests]
c0 = 5 16 keyvault
c1 = 17 17 keyvault
c2 = 25 4 treasure

[shopkeeper]
x = 17
y = 6

[shop]
s0 = 12 potion Shadowmend 10
s1 = 22 weapon Nightsteel_Sword 5 0 0
s2 = 28 armor Shadowplate 0 6 10
s3 = 35 weapon Duskhammer 8 0 0
s4 = 30 shield Duskiron_Shield 0 5 0
s5 = 40 doorkey Umbral_Key

[loot_knight]
d0 = helmet Wraith_Skull 0 2 0 0.4
d1 = chestkey Gloom_Key 0.5
d2 = gold 12 0.8

[loot_archer]
d0 = gloves Shade_Gloves 0 1 0 0.4
d1 = chestkey Gloom_Key 0.5
d2 = gold 18 0.7

[loot_wyvern]
d0 = weapon Wyrm_Fang 8 0 0 1.0
d1 = armor Wyrm_Scale 0 6 20 1.0
d2 = amulet Shadowheart 3 3 15 1.0
d3 = gold 140 1.0

[loot_treasure]
d0 = weapon Duskhammer 8 0 0 0.8
d1 = armor Shadowplate 0 6 10 0.6
d2 = potion Greater_Shadowmend 20 1.0
d3 = gold 70 1.0

[loot_wooden]
d0 = potion Shadowmend 10 0.8
d1 = gloves Shade_Gloves 0 1 0 0.5
d2 = gold 17 1.0

[loot_keyvault]
d0 = doorkey Umbral_Key 1.0
d1 = potion Shadowmend 10 0.7
d2 = gold 22 1.0